services:
  lomnia-ingester:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lomnia-ingester
    network_mode: "host"
    # ports:
    #   - '3010:3010'
    env_file:
      - .env
    volumes:
      - ./plugins.yaml:/app/plugins.yaml:ro
      - ./plugins_state.json:/app/plugins_state.json
    restart: unless-stopped
