[supervisord]
nodaemon=true
user=root

[program:scheduler]
command=/bin/uv run python -m lomnia_ingester scheduler
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:dashboard]
command=/bin/uv run python -m lomnia_ingester dashboard
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
