[browser]
gatherUsageStats = false

[server]
maxUploadSize=2000
port = 3030

[theme]
base="dark"
backgroundColor= "rgb(20, 20, 20)"
primaryColor = "#463695"

[ui]
hideTopBar = true

[client]
toolbarMode = "viewer"
